// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgGtkTAmvwgB9sfg4INKJNGKWr8wZDPY',
    appId: '1:915998427326:web:4a929097ed1e89e8ea76ef',
    messagingSenderId: '915998427326',
    projectId: 'streamcatv1',
    authDomain: 'streamcatv1.firebaseapp.com',
    storageBucket: 'streamcatv1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFcVLUCeOa-l9XEDyiEzAhRLQgWSLbBc',
    appId: '1:915998427326:android:5d1435d5202db8e8ea76ef',
    messagingSenderId: '915998427326',
    projectId: 'streamcatv1',
    storageBucket: 'streamcatv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPcnnv6hGzdF_1M8xUz4BaimEJNVdQN8',
    appId: '1:915998427326:ios:3988e1b579305a0eea76ef',
    messagingSenderId: '915998427326',
    projectId: 'streamcatv1',
    storageBucket: 'streamcatv1.appspot.com',
    iosBundleId: 'com.example.streamcat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkPcnnv6hGzdF_1M8xUz4BaimEJNVdQN8',
    appId: '1:915998427326:ios:3988e1b579305a0eea76ef',
    messagingSenderId: '915998427326',
    projectId: 'streamcatv1',
    storageBucket: 'streamcatv1.appspot.com',
    iosBundleId: 'com.example.streamcat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFgGtkTAmvwgB9sfg4INKJNGKWr8wZDPY',
    appId: '1:915998427326:web:4a929097ed1e89e8ea76ef',
    messagingSenderId: '915998427326',
    projectId: 'streamcatv1',
    authDomain: 'streamcatv1.firebaseapp.com',
    storageBucket: 'streamcatv1.appspot.com',
  );

}